### ISSUE TITLE
请问能否释出 windows 和 linux 版？

### ISSUE THREAD

**Issue by pexcn** [kirainmoe/project-starbeat#1]

**Comment by kirainmoe** [comment]
不会有 Windows 版，因为 Windows 下已经有了官方的控制中心，而且 node-hid 库不支持 Windows 下操作设备：
> Mice and keyboards  
In general you cannot access USB HID keyboards or mice.  
The OS owns these devices.  

Linux 版已经打包并 release，需要 root 权限运行，仅在 ArchLinux 下测试。
