### ISSUE TITLE
你好，我的神舟机器遇到了问题。

### ISSUE THREAD

**Issue by FinchZ** [kirainmoe/project-starbeat#2]
我的机器是炫龙炎魔T2Ti，1年前生产的机器，目前已经停产。
它采用的模具和Z7M-KP7GC是相同的。
我检查了ITE版本，完全一致。
我的操作系统是Manjaro，基于ArchLinux。
在Windows1903下，我的键盘灯不亮，在1803下，表现正常。
我使用了sudo权限，虽然程序运行正常，但是键盘灯仍然不亮。
请问是什么问题？
PS：我的键盘灯启动的时候就不会亮。

**Comment by kirainmoe** [comment]
请检查 BIOS 的键盘灯物理开关是否被关闭。

**Comment by kirainmoe** [comment]
请检查 BIOS 的键盘灯物理开关是否被关闭。

**Comment by FinchZ** [comment]
我找到问题了。当我在windows1803的时候，一切正常。而当我更新到1903的时候，运行失败。
我发现在gamecenter目录下的log文件中有：[ERROR]HID_Manager|GetDevicePath : SetupDiGetDeviceInterfaceDetail failed。
经过查阅资料发现是windows更新带来的问题。
而且我的机型并不与所给代码的机型匹配，所以我准备自己编写驱动。
我下载了usb调试器，并成功捕获了一些数据包，您能给我一些开发指导吗?我已经搭建好了python开发环境和pyusb。
我的QQ：2836365231
谢谢。

**Comment by FinchZ** [comment]
DEVICE ID 048d:ce00 on Bus 001 Address 003 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x200 USB 2.0
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x048d
 idProduct              : 0xce00
 bcdDevice              :    0x2 Device 0.02
 iManufacturer          :    0x1 Error Accessing String
 iProduct               :    0x2 Error Accessing String
 iSerialNumber          :    0x0
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 100 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x3b (59 bytes)
   bNumInterfaces       :    0x2
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :   0x32 (100 mA)
    INTERFACE 0: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x0
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x1
     bInterfaceProtocol :    0x1
     iInterface         :    0x0
    INTERFACE 1: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0
      ENDPOINT 0x81: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
      ENDPOINT 0x2: Interrupt OUT ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x2 OUT
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1

**Comment by kirainmoe** [comment]
你需要使用 `free usb analyzer` 软件的某个特定版本（最新版本可能不兼容 ITE 设备的抓包）来抓取设置键盘灯时的数据包。打开该软件使用 packet view 模式截获对 ITE 设备截获的数据包，然后在 gamingcenter 中解决分别设置不同类型的键盘灯，抓包并分析规律。

具体参见：https://github.com/kirainmoe/hasee-tongfang-macos/issues/28#issuecomment-519640517

晚些时候我会联系你。
