### ISSUE TITLE
Unable to packaging

### ISSUE THREAD

**Issue by 1129921824** [kirainmoe/project-starbeat#4]
![image](https://user-images.githubusercontent.com/20693715/73361291-a1ec9c80-42df-11ea-8d36-d8a893ee4411.png)
一直卡在打包命令上，npm start 后无法找到相应设备，但是用你发布的1.0的版本正常使用

**Comment by kirainmoe** [comment]
没有正确、完整安装 electron 和 electron-packager.

**Comment by 1129921824** [comment]
> 没有正确、完整安装 electron 和 electron-packager.

使用cnpm安装成功，可以cnpm start看到界面

**Comment by kirainmoe** [comment]
确认你的 node-hid 是正常的。在应用程序中按 Ctrl+Shift+I 查看是否报错

**Comment by 1129921824** [comment]
> 确认你的 node-hid 是正常的。在应用程序中按 Ctrl+Shift+I 查看是否报错

使用你的1.0版本正常，我自己编译的不好使
![image](https://user-images.githubusercontent.com/20693715/73518894-7d590780-443a-11ea-936c-9d7562bd38ff.png)

**Comment by kirainmoe** [comment]
> **在应用程序中按 Ctrl+Shift+I 查看是否报错**

**Comment by 1129921824** [comment]
不报错

**Comment by 1129921824** [comment]
可以使用tv远程解决下吗？谢谢啦

**Comment by 1129921824** [comment]
抱歉，刚找到调试界面
![image](https://user-images.githubusercontent.com/20693715/73540857-f02ea680-446b-11ea-9849-13237461fda5.png)
请大佬看看，我已经使用过rebuild和install了

**Comment by kirainmoe** [comment]
用 `yarn install` 安装，或手动用 `npm` 更新 `node-hid`.
